#!/usr/bin/env python3
"""Build the package variant for `packages: !include_dir_named packages`.

The files in homeassistant/packages/ are written for
`packages: !include_dir_merge_named packages/`: each one starts with the name of
its package (`sky_epg:`, `sky_epg_decoders:`, `sky_epg_registrazioni:`) and the
rest is indented by two spaces.

With `!include_dir_named` Home Assistant takes the package name from the file
name, so the same files must have no first line and everything two spaces to the
left. This script writes that variant to homeassistant/packages_include_dir_named/.

Usage (from the root of the repository):
    python3 tools/make_include_dir_named.py           # (re)write the variant
    python3 tools/make_include_dir_named.py --check   # exit 1 if it is out of date

With PyYAML installed, it also checks that each variant file loads to exactly
the content of the package of the original file.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "homeassistant" / "packages"
DST = ROOT / "homeassistant" / "packages_include_dir_named"
INDENT = "  "


def notice(package: str) -> list[str]:
    """Comment lines put on top of every generated file."""
    return [
        "# -----------------------------------------------------------------------------",
        "# VARIANT FOR configuration.yaml WITH   packages: !include_dir_named packages",
        "#",
        "# With !include_dir_named the package name is the file name, so this file has",
        f'# no "{package}:" first line and everything is two spaces to the left.',
        "# Otherwise it is identical to the file with the same name in",
        "# homeassistant/packages/, the version for",
        "#   packages: !include_dir_merge_named packages/",
        "#",
        "# Repository maintainers: this file is generated by",
        "# tools/make_include_dir_named.py, edit the original instead.",
        "# -----------------------------------------------------------------------------",
    ]


def convert(src: Path) -> tuple[str, str]:
    """Return (package name, converted text) for one package file."""
    lines = src.read_text(encoding="utf-8").split("\n")
    # The header is made of comments and blank lines; the first other line is
    # the package name at column 0.
    i = 0
    while i < len(lines) and (not lines[i].strip() or lines[i].startswith("#")):
        i += 1
    if i == len(lines):
        raise SystemExit(f"{src}: no package name found")
    key = lines[i]
    package = key[:-1] if key.endswith(":") and " " not in key else ""
    if package != src.stem:
        raise SystemExit(
            f'{src}: the first key must be "{src.stem}:" (found "{key}")'
        )
    body = []
    for n, line in enumerate(lines[i + 1 :], start=i + 2):
        if not line.strip():
            body.append("")
        elif line.startswith(INDENT):
            body.append(line[len(INDENT) :])
        else:
            raise SystemExit(
                f"{src}:{n}: everything after the package name must be indented "
                f"by at least two spaces"
            )
    text = "\n".join(notice(package) + lines[:i] + body)
    return package, text


def yaml_check(src: Path, package: str, text: str) -> None:
    """Both versions must load to the same package configuration."""
    try:
        import yaml  # type: ignore[import-untyped]
    except ImportError:
        return
    original = yaml.safe_load(src.read_text(encoding="utf-8"))
    variant = yaml.safe_load(text)
    if original != {package: variant}:
        raise SystemExit(f"{src.name}: the variant does not load to the same content")


def main() -> int:
    check = "--check" in sys.argv[1:]
    sources = sorted(SRC.glob("*.yaml"))
    if not sources:
        raise SystemExit(f"no package files in {SRC}")
    expected = {}
    for src in sources:
        package, text = convert(src)
        yaml_check(src, package, text)
        expected[src.name] = text

    stale = []
    for name, text in expected.items():
        dst = DST / name
        if not dst.exists() or dst.read_text(encoding="utf-8") != text:
            stale.append(name)
    extra = sorted(
        p.name for p in DST.glob("*.yaml") if p.name not in expected
    ) if DST.exists() else []

    if check:
        if stale or extra:
            for name in stale:
                print(f"out of date: homeassistant/packages_include_dir_named/{name}")
            for name in extra:
                print(f"no original: homeassistant/packages_include_dir_named/{name}")
            print("run: python3 tools/make_include_dir_named.py")
            return 1
        print(f"ok: {len(expected)} files in sync")
        return 0

    DST.mkdir(parents=True, exist_ok=True)
    for name in stale:
        (DST / name).write_text(expected[name], encoding="utf-8")
        print(f"written: homeassistant/packages_include_dir_named/{name}")
    for name in extra:
        print(f"warning: no original for homeassistant/packages_include_dir_named/{name}")
    if not stale:
        print(f"ok: {len(expected)} files already in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
